services:

  todos-api:
    build: .
    environment:
      - PORT=3000
      - DB_CONNECTION_STRING=postgres://postgres:postgres@todos-db/postgres
    ports:
      - '3000:3000'
    depends_on:
      - todos-db
    networks:
      - backend

  todos-db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  backend: