apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: todos-db
  template:
    metadata:
      labels:
        component: todos-db
    spec:
      containers:
        - name: todos-db
          image: postgres:16-alpine
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "postgres"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: todos-db
spec:
  selector:
    component: todos-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP